export { MangaDetailHeader } from './MangaDetailHeader';
export { CoverImage } from './CoverImage';
export { TitleSection } from './TitleSection';
export { StatsCard } from './StatsCard';
export { ContinueReadingButton } from './ContinueReadingButton';
export { AuthorsSection } from './AuthorsSection';
export { GenresSection } from './GenresSection';
export { DescriptionSection } from './DescriptionSection';
export { ChaptersList } from './ChaptersList';
